import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Question Bank Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-(family-name:--font-geist-sans) ${geistSans.variable} ${geistMono.variable} antialiased max-w-[1920px] mx-auto border-4 border-red-500`}
      >
      <ThemeProvider attribute="class" enableSystem defaultTheme="system">
        {children}
        </ThemeProvider>  
      </body>
    </html>
  );
}
