import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes"
const poppinsSans = Poppins({
  variable: "--font-poppins-primary",
  subsets: ["latin"],
   weight: ["400", "600"],

});
const robotoMono = Roboto({
  variable: "--font-roboto-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Question Bank Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppinsSans.variable} ${robotoMono.variable}  antialiased max-w-[1920px] mx-auto border-4 border-red-500`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
        {children}
        </ThemeProvider>  
      </body>
    </html>
  );
}
